# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: 100.64.99.139:5000/salaboy/spring-cloud-k8s-minion
  tag: 1.0.14
  pullPolicy: IfNotPresent
service:
  name: spring-cloud-k8s-minion
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "true"
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 400m
    memory: 512Mi
probePath: /actuator/health
livenessProbe:
  initialDelaySeconds: 90
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10
